[build]
  command = "pip install -r requirements.txt && python app.py"
  functions = "netlify/functions"
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.10"

[[plugins]]
  package = "@netlify/plugin-python"