services:
  - type: web
    name: food-allergy-site
    env: python
    buildCommand: |
      pip install -r requirements.txt
      # Tesseract本体をインストール
      apt-get update && apt-get install -y tesseract-ocr tesseract-ocr-jpn
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 10000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
